version: "3.9"

services:
  dashboard-db:
    container_name: dashboard-db
    image: postgres:11.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  dashboard-backend:
    container_name: dashboard-backend
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - dashboard-db
    command: /bin/sh -c "/scripts/entrypoint.sh"
    env_file:
      - .env

  dashboard-frontend:
    container_name: dashboard-frontend
    build:
      context: .
      dockerfile: config/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - dashboard-backend
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public
    env_file:
      - ./frontend/.env

volumes:
  db-data:
