# Generated by Django 3.2.6 on 2021-08-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(null=True)),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="dashboard.datasource",
                    ),
                ),
            ],
        ),
    ]
